### ISSUE TITLE
Where is the .env file loaded?

### ISSUE THREAD

**Issue by dominikwilkowski** [Bechma/realworld-leptos#3]
Been looking through this excellent resource and wonder where you're loading the `.env` file? I can see `dotenv` in the lock file but no where else and it seems to be a transitive dependency from the sqlx packages?

**Comment by Bechma** [comment]
Hello, glad you like the project!

I don't use `dotenv` to load the environmental variables, I prefer to export and use them without any extra dependency.
You see that in `Cargo.lock` because any of the dependencies(or the dependency of another dependency) use it, but, if it's not declared in `Cargo.toml`, the application doesn't need it.

As extra, I can tell that when you deploy the project, you don't need to load anything from .env , it's only for deployment:

![image](https://github.com/user-attachments/assets/f530999b-11d9-43d1-8fe8-891b336f9a00)
This screenshot is from the render project where the application is deployed

**Comment by dominikwilkowski** [comment]
Ok that makes sense. Thanks.
Been working on file uploads now. Have you come across that yet via server functions?
Closing this issue as it answered the original questions

**Comment by Bechma** [comment]
I didn't use any file upload, but you can find an example here: https://github.com/leptos-rs/leptos/blob/1d99764740cd04532bcca245a317aa00c9099589/examples/server_fns_axum/src/app.rs#L332 
Hope it helps :)
